orders/urls.py
from django.urls import path, re_path

from . import views

app_name="orders"

urlpatterns = [
    path("", views.index, name="index"),
    path("menu", views.menu, name="menu"),
    path("order", views.get_order, name="order"),
    path("cart", views.cart, name="cart"),
    path("info", views.info, name="info"),
    path("payment/",views.pay, name="pay"),
    path("validate_payment",views.validate, name="validate"),
    path("monitor", views.monitor, name="monitor"),
    path("order_pizza", views.order_pizza, name="order_pizza"),
    path("order_salad", views.order_salad, name="order_salad"),
    path("order_pasta", views.order_pasta, name="order_pasta"),
    path("order_sub", views.order_sub, name="order_sub"),
    path("order_plate", views.order_plate, name="order_plate"),
    re_path(r'^done/(?P<pk>[0-9]+)/$', views.done, name='done')
]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    path("login", include("users.urls")), #TODO: vérifier si utile
    path("logout", include("users.urls"))
]

orders/forms.py
from django import forms
from .models import Topping, Salad, Pasta, Sub_main, Sub_addon, Plate

PIZZA_TYPES = (
('R','Regular'),
('S', 'Sicilian')
)

PIZZA_SIZES = (
('S','Small'),
('L','Large')
)

SUB_SIZES = (
('S','Small'),
('L','Large')
)

PLATE_SIZES = (
('S','Small'),
('L','Large')
)

class PizzaForm(forms.Form):
    pizza_type = forms.ChoiceField(choices=PIZZA_TYPES, widget=forms.RadioSelect, label="Pizza Type")
    pizza_size = forms.ChoiceField(choices=PIZZA_SIZES, widget=forms.RadioSelect, label="Pizza Size")
    toppings = forms.ModelMultipleChoiceField(queryset = Topping.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)

class SaladForm(forms.Form):
    salad_type = forms.ModelChoiceField(queryset=Salad.objects.all(),
                label="Salad Type")

class PastaForm(forms.Form):
    pasta_type = forms.ModelChoiceField(queryset=Pasta.objects.all(),
                label="Pasta Type")

class SubForm(forms.Form):
    sub_main = forms.ModelChoiceField(queryset=Sub_main.objects.all(),
                label="Sub Type")
    sub_size = forms.ChoiceField(choices=SUB_SIZES, widget=forms.RadioSelect, label="Sub Size")
    toppings = forms.ModelMultipleChoiceField(queryset = Sub_addon.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)

class PlateForm(forms.Form):
    type = forms.ModelChoiceField(queryset=Plate.objects.exclude(size='L'), label = "Plate Type")
    plate_size = forms.ChoiceField(choices= PLATE_SIZES, widget=forms.RadioSelect, label="Plate Size")

orders/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import permission_required

from .forms import PizzaForm, SaladForm, PastaForm, SubForm, PlateForm
from .models import Topping, Pizza, Order, Pasta, Salad, Sub, Sub_main, Sub_addon, Plate, PlateOrder, SaladOrder, PizzaPrice, PastaOrder

import logging

logger = logging.getLogger(__name__)

def index(request):
    return render(request, "orders/index.html",{})

def menu(request):
    #data on subs
    plain_subs = Sub.objects.exclude(addons__isnull=False).order_by('main')
    #data on pizzas
    regular_prices={}
    for n_tops in range(5):
        regular_prices[n_tops] = []
        for size in ['S','L']:
              p = PizzaPrice.objects.get(pizza_type='R',pizza_size=size,n_tops=n_tops).price
              #TODO ajouter des choses pour vérifier que ça se passe bien (requete existe et unique)
              regular_prices[n_tops].append(p)
    sicilian_prices={}
    for n_tops in range(5):
        sicilian_prices[n_tops] = []
        for size in ['S','L']:
              p = PizzaPrice.objects.get(pizza_type='S',pizza_size=size,n_tops=n_tops).price
              #TODO ajouter des choses pour vérifier que ça se passe bien
              sicilian_prices[n_tops].append(p)
    # plates
    plates_prices = {}
    plate_type = [str(el.type) for el in Plate.objects.exclude(size='L')]
    for el in plate_type:
        plates_prices[el] = []
        for size in ['S', 'L']:
            p = Plate.objects.get(type=el, size=size).price
            plates_prices[el].append(p)
    context = {"Pastas":Pasta.objects.all(),
                'Pizza_header':['', 'Small','Large'],
                'R_rows':regular_prices,
                'S_rows':sicilian_prices,
                "Salads":Salad.objects.all(),
                "Subs": Sub_main.objects.all(),
                "Sub_addons":Sub_addon.objects.all(),
                "Toppings": Topping.objects.all(),
                "Plate_prices": plates_prices}
    return render(request, "orders/menu.html",context)

def info(request):
    return render(request, "orders/info.html",{})

def cart(request):
    """This function takes to cart page"""
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(client=request.user,payment_status=False) #TODO doit-on garder ces create ?
        context = {"order":order.all_food(),
        "price": order.compute_price()}
    else:
        if 'order_id' in request.session:
            order = Order.objects.get(pk=request.session['order_id'])
            context = {"order":order.all_food(),
            "price": order.compute_price()}
        else:
            context = {"order":["No order yet"],
                        "price":0}
    return render(request, "orders/cart.html", context)

def pay(request):
    """This function takes to payment page"""
    if request.user.is_authenticated:
        context = {"price":request.GET.get('price')}
        return render(request, "orders/payment.html", context)
    else:
        request.session['order_finished'] = True
        return render(request, "users/login.html", {"message": "Log in to validate your order"})

def get_order(request):
    pizza_form = PizzaForm({'pizza_type':'R','pizza_size':'S'})
    salad_form = SaladForm()
    pasta_form = PastaForm()
    sub_form = SubForm()
    plate_form = PlateForm()
    return render(request, 'orders/order.html',
            {'pizza_form': pizza_form, 'salad_form': salad_form,
             'pasta_form': pasta_form, 'sub_form':sub_form,
             'plate_form': plate_form})

def order_pizza(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        pizza_form = PizzaForm(request.POST)
        # check whether it's valid:
        if pizza_form.is_valid():
            # process the data in form.cleaned_data as required
            pizza = Pizza.objects.create(pizza_type=pizza_form.cleaned_data['pizza_type'],pizza_size=pizza_form.cleaned_data['pizza_size'])
            for top in pizza_form.cleaned_data['toppings']:
                    top_obj = Topping.objects.get(type=top)
                    pizza.toppings.add(top_obj)
            pizza.save()

            #add to order or create
            if request.user.is_authenticated:
                order, created = Order.objects.get_or_create(client=request.user,payment_status=False)
            else:
                if 'order_id' in request.session:
                    pk = request.session['order_id']
                    order = Order.objects.get(pk=pk)
                else:
                    order = Order(payment_status=False)
                    order.save()
                    request.session['order_id']=order.pk
            order.pizzas.add(pizza)
            # redirect to a new URL:
            return HttpResponseRedirect('cart')
        else:
            pass #TODO
    else:
        return render(request, 'orders/error.html') #TODO ajouter page erreur

def order_salad(request):
    logger.warning("I am in salad")
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        salad_form = SaladForm(request.POST)
        # check whether it's valid:
        if salad_form.is_valid():
            logger.warning(salad_form.cleaned_data["salad_type"])
            # process the data in form.cleaned_data as required
            #add to order or create
            if request.user.is_authenticated:
                order, created = Order.objects.get_or_create(
                                    client=request.user,payment_status=False)
            else:
                if 'order_id' in request.session:
                    pk = request.session['order_id']
                    order = Order.objects.get(pk=pk)
                else:
                    order = Order(payment_status=False)
                    order.save()
                    request.session['order_id']=order.pk

            s = SaladOrder(salad=salad_form.cleaned_data["salad_type"], order=order)
            s.save()
            # redirect to a new URL:
            return HttpResponseRedirect('cart')
    else:
        return render(request, 'orders/error.html') #TODO

def order_pasta(request):
    # TODO: gérer quand on est pas loggé.
    logger.warning("I am in order_pasta")
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        pasta_form = PastaForm(request.POST)
        logger.warning("there")
        # check whether it's valid:
        if pasta_form.is_valid():
            logger.warning(pasta_form.cleaned_data["pasta_type"])
            # process the data in form.cleaned_data as required
            if request.user.is_authenticated:
                order, created = Order.objects.get_or_create(
                                    client=request.user,payment_status=False)
            else:
                if 'order_id' in request.session:
                    pk = request.session['order_id']
                    order = Order.objects.get(pk=pk)
                else:
                    order = Order(payment_status=False)
                    order.save()
                    request.session['order_id']=order.pk
            p = PastaOrder(pasta=pasta_form.cleaned_data["pasta_type"], order=order)
            p.save()
            # redirect to a new URL:
            return HttpResponseRedirect('cart')
    else:
        return render(request, 'orders/error.html') #TODO

def order_sub(request):
    logger.warning("I am in order_sub")
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        sub_form = SubForm(request.POST)
        # check whether it's valid:
        if sub_form.is_valid():
            logger.warning(sub_form.cleaned_data["sub_main"])
            # process the data in form.cleaned_data as required
            sub = Sub.objects.create(main=sub_form.cleaned_data['sub_main'],
                                     size=sub_form.cleaned_data['sub_size'])
            for top in sub_form.cleaned_data["toppings"]:
                top_obj = Sub_addon.objects.get(type=top)
                sub.addons.add(top_obj)
            sub.save()
            #add to order or create
            if request.user.is_authenticated:
                order, created = Order.objects.get_or_create(
                                    client=request.user,payment_status=False)
            else:
                if 'order_id' in request.session:
                    pk = request.session['order_id']
                    order = Order.objects.get(pk=pk)
                else:
                    order = Order(payment_status=False)
                    order.save()
                    request.session['order_id']=order.pk
            order.subs.add(sub)
            # redirect to a new URL:
            return HttpResponseRedirect('cart')
    else:
        return render(request, 'orders/error.html') #TODO

def order_plate(request):
    logger.warning("I am in order_plate")
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        plate_form = PlateForm(request.POST)
        # check whether it's valid:
        if plate_form.is_valid():
            logger.warning(plate_form.cleaned_data["type"])
            # process the data in form.cleaned_data as required
            plate = Plate.objects.get(type=plate_form.cleaned_data["type"],
                            size = plate_form.cleaned_data['plate_size'])

            #add to order or create
            if request.user.is_authenticated:
                order, created = Order.objects.get_or_create(
                                    client=request.user,payment_status=False)
            else:
                if 'order_id' in request.session:

orders/templates/orders/admin.html
{% extends "orders/layout.html" %}

{% block title %}Admin{% endblock %}
{% block content %}
<div class="container">
  <div class="fond">
    <div class="row">
      <div class="col md-12">
        <h4 class="menu_title">Pending orders</h4>
      </div>
    </div>
    <div class="row">
      <div class="col md-12">
        <ul>
          {% for o in orders %}
          <li>{{o.order.client}}:
          <ul>
            {% for p in o.food %}
            <li>{{ p }}</li>
            {% endfor %}
          </ul>
          <form action="{% url 'orders:done' o.order.pk %}" method="post">
            {% csrf_token %}
            <input class="try_it" type="submit" value="Mark as completed">
          </form>
          </li>
          <br>
          <br>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/cart.html
{% extends "orders/layout.html" %}

{% block title %}Cart{% endblock %}
{% block content %}

<div class="container">
  <div class="fond">
    <div class="row">
      <div class="col md-12">
        <h4 class="menu_title">Here is your cart</h4>
      </div>
    </div>
    <div class="row">
      <div class="col md-12">
        <ul>
          {% for p in order %}
          <li>{{ p }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col md-12 price">
        Total price : ${{ price }}
      </div>
    </div>
    <div class="row">
      <div class="col md-6 cart-option">
        <a href="/order" > Continue order </a>
      </div>
      <div class="col md-6 cart-option">
        <a href="/payment/?price={{ price }}" > Proceed to Payment </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/index.html
{% extends "orders/layout.html" %}

{% block title %}Index{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <h1 id="title">Pinocchio’s Pizza</h1>
  </div>
  <div class="row">
    <p id="text_index">We have been feeding Harvard for over 50 years.</p>
  </div>
  <div class="row">
    <p id="text_index">We sell award-winning sicilian-style pizza.
    </p>
  </div>
  <div class="row">
    <p id="text_index" style="margin-bottom:30px">We are Pinocchio’s.</p>
  </div>

  <div class="row">
      <a href="/order" class="try_it index">Order now!</a>
  </div>
</div>

{% endblock %}

orders/templates/orders/info.html
{% extends "orders/layout.html" %}

{% block title %}Info{% endblock %}

{% block content %}
<div class="container">
  <div class="fond">
    <div class="row" style="margin-bottom:80px">
      <h4 class="menu_title">Where to find us?</h4>
    </div>
    <div class="row">
      <div class="col md-6 my-auto adress">
        <p>74 Winthrop Street <br>
        Harvard Square <br>
        617-876-4897</p>
      </div>
      <div class="col md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2947.617322891313!2d-71.12255418454338!3d42.3719940791861!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e3775d51d69b07%3A0xa4d76bff98604ad5!2s74%20Winthrop%20St%2C%20Cambridge%2C%20MA%2002138!5e0!3m2!1sfr!2sus!4v1594138952932!5m2!1sfr!2sus" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700&family=Rye&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'orders/style.css' %}">
    <script src="{% static 'orders/navigation.js' %}"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon_pizza.png' %}"/>
  </head>
  <body>
<!-- Navigation -->
<div class="container">
  <div class="row">
    <div class="col-sm-1">
      <a href="/cart"><i class="fa fa-shopping-cart" id="cart_icon"></i>{% if cart_isfull %} <span class='badge badge-warning' id='lblCartCount'>{{n_cart}}</span>{% endif %}</a>
    </div>
    <div class="col-sm-1">
      <a href="/login" id="login_link">{% if request.user.is_authenticated %} Logout {% else %} Login {% endif %}</a>
    </div>
    <div class="col-sm-8">
        <ul id="navbar">
          <!-- <li id="navitem" {% if "/cart" in request.path %}class="active"{% endif %}><a href="/cart">Cart</a></li>
          <li id="navitem" {% if "/login" in request.path %}class="active"{% endif %}><a href="/login">Login</a></li> -->
          <li id="navitem" {% if request.path == "/" %}class="active"{% endif %}><a href="/">Home</a></li>
          <li id="navitem" {% if "/menu" in request.path %}class="active"{% endif %}><a href="/menu">Menu</a></li>
          <li id="navitem" {% if "/order" in request.path %}class="active"{% endif %}><a href="/order">Order</a></li>
          <li id="navitem" {% if "/info" in request.path %}class="active"{% endif %}><a href="/info">Info</a></li>
        </ul>
    </div>
    <div class="col-sm-2">
      <a href="/order" class="try_it">Try it now!</a>
    </div>
  </div>

</div>
  <div id="content">{% block content %}{{ active_page }}{% endblock %}</div>
  <br>
  <br>
  <div id="footer">
      {% block footer %}
      &copy; Copyright 2020 by <a href="mailto:arnaud.buisson@hec.edu">BSN</a>.
      {% endblock %}
  </div>
  </body>
</html>

orders/templates/orders/menu.html
{% extends "orders/layout.html" %}

{% block title %}Menu{% endblock %}

{% block content %}

<div class="container">
  <div class="row fond tab">
    <div class="col-md-1">
    </div>
    <div class="col-md-2">
      <button class="tablink active">Pizza</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Subs</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Pasta</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Salads</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Platter</button>
    </div>
    <div class="col-md-1">
    </div>
  </div>
  <div class="fond">
    <div id="Pizza" class="Menucontent">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6">
              <h4 class="menu_title">Regular pizza</h4>
              <table class="table table_menu">
                <thead>
                  <tr>
                    {% for k in Pizza_header %}
                    <th>{{k}}</th>
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                  {% for k,v in R_rows.items %}
                  <tr>
                    <td>{% if k == 0 %}Cheese{% elif k == 1 %}1 topping{% elif k == 4%} Special {% else %}{{k}} toppings{% endif %}</td>
                    {% for e in v %}
                    <td>${{e}}</td>
                    {% endfor %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="col-md-6">
              <h4 class="menu_title">Sicilian pizza</h4>
              <table class="table">
                <thead>
                  <tr>
                    {% for k in Pizza_header %}
                    <th>{{k}}</th>
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                  {% for k,v in S_rows.items %}
                  <tr>
                    <td>{% if k == 0 %}Cheese{% elif k == 1 %}1 topping{% elif k == 4%} Special {% else %}{{k}} toppings{% endif %}</td>
                    {% for e in v %}
                    <td>${{e}}</td>
                    {% endfor %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h4 class="menu_title">Our toppings</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="toppings_list">
            {% for t in Toppings %}
            <li> {{ t.type }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <div id="Subs" class="Menucontent">
      <div class="row">
        <div class="col-md-6">
          <h4 class="menu_title">Subs</h4>
        </div>
        <div class="col-md-6">
          <h4 class="menu_title">Add to your sandwich</h4>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <table>
            <tr>
              <th></th>
              <th>Small</th>
              <th>Large</th>
            </tr>
            {% for s in Subs %}
            <tr>
              <td>{{ s.name }}</td>
              <td>{% if s.price_s > 0 %}{{ s.price_s }}{% endif %}</td>
              <td>{{ s.price_l }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
        <div class="col-md-6">

          <ul class="list-menu">
            {% for s in Sub_addons %}
            <li> {{ s.type }} + $ {{ s.price }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <div id="Pasta" class="Menucontent">
      <h4 class="menu_title">Pasta</h4>
      <ul class="list-menu">
        {% for pasta in Pastas %}
        <li>{{ pasta.type }} at $ {{ pasta.price }}</li>
        {% endfor %}
      </ul>
    </div>

    <div id="Salads" class="Menucontent">
      <h4 class="menu_title">Salads</h4>
      <ul class="list-menu">
        {% for salad in Salads %}
        <li>{{ salad.type }} at $ {{ salad.price }}</li>
        {% endfor %}
      </ul>
    </div>

    <div id="Platter" class="Menucontent">
      <h4 class="menu_title">Platter</h4>
      <div class="">
        <table style="width:50%">
          <tr>
            <th></th>
            <th>Small</th>
            <th>Large</th>
          </tr>
          {% for n, v in Plate_prices.items %}
          <tr>
            <td> {{ n }} </td>
            {% for e in v %}
            <td>${{e}}</td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/order.html
{% extends "orders/layout.html" %}

{% block title %}Order{% endblock %}

{% block content %}
<div class="container">
  <div class="row fond tab">
    <div class="col-md-1">
    </div>
    <div class="col-md-2">
      <button class="tablink active">Pizza</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Subs</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Pasta</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Salads</button>
    </div>
    <div class="col-md-2">
      <button class="tablink">Platter</button>
    </div>
    <div class="col-md-1">
    </div>
  </div>


  <div class="fond">
    <div id="Pizza" class="Menucontent">
      <form action="/order_pizza" method="post">
        {% csrf_token %}
        {{ pizza_form.non_field_errors }}
        <div class="row">
          <div class="col-md-4 fieldWrapper">
              {{ pizza_form.pizza_type.errors }}
              <label for="{{ pizza_form.pizza_type.id_for_label }}">Pizza type:</label>
              {{ pizza_form.pizza_type }}
          </div>
          <div class="col-md-4 fieldWrapper">
              {{ pizza_form.pizza_size.errors }}
              <label for="{{ pizza_form.pizza_size.id_for_label }}">Pizza size:</label>
              {{ pizza_form.pizza_size }}
          </div>
        </div>
        <div class="row">
          <div class="fieldWrapper">
              {{ pizza_form.toppings.errors }}
              <label for="{{ pizza_form.toppings.id_for_label }}">Choix de toppings: </label>
              {{ pizza_form.toppings }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <input class="try_it" type="submit" value="Add to cart">
          </div>
        </div>
      </form>
    </div>

    <div id="Subs" class="Menucontent">
      <form action="/order_sub" method="post">
        {% csrf_token %}
        {{ sub_form.non_field_errors }}
        <div class="row">
          <div class="col-md-4 fieldWrapper">
              {{ sub_form.sub_main.errors }}
              <label for="{{ sub_form.sub_main.id_for_label }}">Sub type:</label>
              {{ sub_form.sub_main }}
          </div>
          <div class="col-md-4 fieldWrapper">
              {{ sub_form.sub_size.errors }}
              <label for="{{ sub_form.sub_size.id_for_label }}">Sub size:</label>
              {{ sub_form.sub_size }}
          </div>
        </div>
        <div class="row">
          <div class="fieldWrapper">
              {{ sub_form.toppings.errors }}
              <label for="{{ sub_form.toppings.id_for_label }}">Choix de toppings: </label>
              {{ sub_form.toppings }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <input class="try_it" type="submit" value="Add to cart">
          </div>
        </div>
      </form>
    </div>


<div id="Pasta" class="Menucontent">
  <h3>Pasta</h3>
  <form action="/order_pasta" method="post">
    {% csrf_token %}
    {{ pasta_form }}
      <input type="submit" value="Submit">
  </form>
</div>

    <div id="Salads" class="Menucontent">
      <h3>Salads</h3>
      <form action="/order_salad" method="post">
        {% csrf_token %}
        {{ salad_form }}
        <input type="submit" value="Submit">
      </form>
    </div>

    <div id="Platter" class="Menucontent">
      <form action="/order_plate" method="post">
        {% csrf_token %}
        {{ plate_form.non_field_errors }}
        <div class="row">
          <div class="col-md-4 fieldWrapper">
              {{ plate_form.type.errors }}
              <label for="{{ plate_form.type.id_for_label }}">Plate type:</label>
              {{ plate_form.type }}
          </div>
          <div class="col-md-4 fieldWrapper">
              {{ plate_form.plate_size.errors }}
              <label for="{{ plate_form.plate_size.id_for_label }}">Plate size:</label>
              {{plate_form.plate_size}}
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <input class="try_it" type="submit" value="Add to cart">
          </div>
        </div>
      </form>
    </div>

  </div>
</div>
{% endblock %}

orders/templates/orders/payment.html
{% extends "orders/layout.html" %}

{% block title %}Payment{% endblock %}
{% block content %}
<div class="container">
  <div class="fond">
    <div class="row">
      <div class="col md-12">
        <h4 class="menu_title">You're one step before a memorable gourmet journey </h4>
      </div>
    </div>
    <div class="row">
      <div class="col md-12 price">
        Total amount charged : ${{ price }}
      </div>
    </div>
    <div class="row">
      <div class="col md-12">
        <form id="payment-form" class="sr-payment-form">
          {% csrf_token %}
          <div class="sr-combo-inputs-row">
            <div class="sr-input sr-card-element" id="card-element"></div>
          </div>
          <div class="sr-field-error" id="card-errors" role="alert"></div>
          <button id="submit" class="btn">
            <div class="spinner-border  spinner-border-sm text-light hidden" id="spinner" role="status">
              <span class="sr-only">Loading...</span>
            </div>
            <span class="try_it" id="button-text">Pay</span><span id="order-amount"></span>
          </button>
        </form>
      </div>
    </div>
    <form id="payload" class="hidden" action="/payment-complete" method="post">
      {% csrf_token %}
      <input id ="data-payload" type="hidden" name="payload"/>
    </form>

    <div class="row">
      <div class="col md-12 cart-option">
        <a href="/validate_payment">Validate Payment</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/thankyou.html
{% extends "orders/layout.html" %}

{% block title %}Thank you!{% endblock %}
{% block content %}
<div class="container">
  <div class="fond">
  <div class="row">
    <div class="col md-12">
      <h4 class="menu_title">Thank you!</h4>
    </div>
  </div>
  <div class="row">
    <div class="col md-12">
      Thank you {{ client }} ! Your order is on the way :)
    </div>
  </div>
  <div class="row">
    <div class="col md-12 cart-option">
      <a href="/">Back to main page</a>
    </div>
  </div>

</div>
</div>
{% endblock %}